databases:
  - name: dpifinal
    plan: free
    databaseName: dpifinal
    user: dpifinal

services:
  - type: web
    name: dpifinal
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dpifinal
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
